  
name: Base Pipeline

on: pull_request

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node.JS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install Node Dependencies
      run: npm install
    - name: Test Code Linting
      run: npm run lint
    - name: Save Code Linting Report JSON
      run: npm run lint:report
      continue-on-error: true
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@1.0.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        report-json: "eslint_report.json"
    - name: Upload ESLint report
      uses: actions/upload-artifact@v1
      with:
        name: eslint_report.json
        path: eslint_report.json

  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node.JS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install Node Dependencies
      run: npm install
    - name: Run Jest
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"