name: Documentation and Coverage Reporter Pipeline

on: 
  push:
    branches: [ develop ]

jobs:
  Updating-Documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node.JS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install Node Dependencies
      run: npm install
    - name: Generate API Documentation
      run: npm run docs:build
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "docs"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_WIKI_TOKEN }}
        
  coverage-reporter:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node Dependencies
      run: npm install
    - name: Generate coverage report
      run: npm run test:coverage
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/clover.xml
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: npm run test:coverage
        coverageLocations: ${{ github.workspace }}/coverage/lcov.info:lcov