name: Documentation Pipeline

on: 
  push:
    branches: [ develop ]

jobs:
  Updating-Documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node.JS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install Node Dependencies
      run: npm install
    - name: Generate API Documentation
      run: npm run docs:build
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "docs"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_WIKI_TOKEN }}