  
name: Puppeteer Test

on: push

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node.JS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install Dependencies
      uses: actions/npm@master
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install
    - name: Build
      run: npm run build
    - name: Test Code
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
      with:
        args: npm run test