  
name: Puppeteer Test

on: push

jobs:
  end_to_end_tests:
    name: Run Headful End-to-End Tests 
    runs-on: ubuntu-latest

    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      CI: 'true'
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install node 
      uses: actions/setup-node@v2-beta
      with:
        node-version: "12.x"

    - name: Install Dependencies 
      run: npm install

    - name: Run headful puppeteer tests
      uses: djp3/puppeteer-headful@master
      with:
        args: npm run pup